In [3]:
import pandas as pd
file = 'G:/Mon Drive/PCO/data/'

In [111]:
dtypes = {
    'CRO':str,
    'id_med' : int,
    'id_diag': int,
    'source':str,
    'nir':str,
    'operation':str
}

CRO_1 = pd.read_csv(f'{file}\CRO_1.csv', sep=';', dtype=str)
print('nb de CRO_1 total:', len(CRO_1))
CRO_2_1 = pd.read_csv(f'{file}\CRO_2_1.csv', sep=';', dtype=str)
print('nb de CRO_2_1 total:', len(CRO_2_1))
CRO_2_2 = pd.read_csv(f'{file}\CRO_2_2.csv', sep=';', dtype=str)
print('nb de CRO_2_2 total:', len(CRO_2_2))
CRO_3 = pd.read_csv(f'{file}\CRO_3.csv', sep=';', dtype=dtypes)
print('nb de CRO_3 total:', len(CRO_3))
CRO_4 = pd.read_csv(f'{file}\CRO_4.csv', sep=';', dtype=dtypes)
print('nb de CRO_4 total:', len(CRO_4))
CRO_5 = pd.read_csv(f'{file}\CRO_5.csv', sep=';', dtype=str)
print('nb de CRO_5 total:', len(CRO_5))
print(len(CRO_1) + len(CRO_2_1) + len(CRO_2_2) + len(CRO_3) + len(CRO_4) + len(CRO_5))

nb de CRO_1 total: 7061
nb de CRO_2_1 total: 5830
nb de CRO_2_2 total: 5603
nb de CRO_3 total: 2306
nb de CRO_4 total: 2326
nb de CRO_5 total: 6471
29597

In [21]:
CRO_1_et_2 = pd.concat([CRO_1, CRO_2_1, CRO_2_2], ignore_index=True)
len(CRO_1_et_2)

18494

In [22]:
diags_correspondance = pd.read_csv(f'../data/old_id_diag.csv', sep=';', dtype=str)
diags_correspondance

   id_diag_old id_diag
0            0     277
1            1      78
2            2     183
3            3      81
4            4     159
..         ...     ...
64          64     323
65          65     328
66          66     271
67          67     126
68          68     175

[69 rows x 2 columns]

In [23]:
CRO_1_et_2 = pd.merge(CRO_1_et_2, diags_correspondance, left_on="id_diag", right_on='id_diag_old', how='left')
CRO_1_et_2.head(5)

,CRO,TNM,id_diag_x,id_med,nir,source,operation,id_diag_old,id_diag_y
0,Compte rendu d'histopathologie\nDr Valentine B...,NaN,68,79,2 2002 06 76416 623 45,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,68,175
1,Compte rendu d'histopathologie\nDr Adrienne Pa...,NaN,41,77,2 1955 06 74182 824 18,huggingChat/meta-llama/Llama-2-70b-chat-hf,biopsie,41,72
2,Compte rendu d'histopathologie\nDr Anouk Weiss...,pT2 N0 Mx,45,70,1 1956 01 73544 037 28,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,45,2
3,Compte rendu d'histopathologie\nDr Michelle Va...,NaN,19,62,1 1973 02 20392 432 73,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,19,262
4,Compte rendu d'histopathologie\nLe présent rap...,NaN,55,3,2 1955 06 74182 824 18,huggingChat/meta-llama/Llama-2-70b-chat-hf,biopsie,55,32

In [25]:
CRO_1_et_2 = CRO_1_et_2.drop(['TNM', 'id_diag_x', 'id_diag_old'], axis=1)
CRO_1_et_2 = CRO_1_et_2.rename(columns = {"id_diag_y" : 'id_diag'})
CRO_1_et_2

,CRO,id_med,nir,source,operation,id_diag
0,Compte rendu d'histopathologie\nDr Valentine B...,79,2 2002 06 76416 623 45,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,175
1,Compte rendu d'histopathologie\nDr Adrienne Pa...,77,2 1955 06 74182 824 18,huggingChat/meta-llama/Llama-2-70b-chat-hf,biopsie,72
2,Compte rendu d'histopathologie\nDr Anouk Weiss...,70,1 1956 01 73544 037 28,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,2
3,Compte rendu d'histopathologie\nDr Michelle Va...,62,1 1973 02 20392 432 73,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,262
4,Compte rendu d'histopathologie\nLe présent rap...,3,2 1955 06 74182 824 18,huggingChat/meta-llama/Llama-2-70b-chat-hf,biopsie,32
...,...,...,...,...,...,...
18489,Compte-rendu d’Histopathologie\nPatient : Jacq...,38,1 1951 09 97158 729 33,huggingChat/mistralai/Mixtral-8x7B-Instruct-v0.1,biopsie,86
18490,Compte Rendu d'Histopathologie\nPatient : Benj...,15,1 1956 06 42957 101 18,huggingChat/mistralai/Mixtral-8x7B-Instruct-v0.1,exérèse,46
18491,Compte-rendu d'Histopathologie\nPatient : M. B...,15,1 1956 06 42957 101 18,huggingChat/mistralai/Mixtral-8x7B-Instruct-v0.1,exérèse,46
18492,Compte-rendu d'Histopathologie\nPatient : Marg...,34,2 1935 05 53360 913 32,huggingChat/mistralai/Mixtral-8x7B-Instruct-v0.1,biopsie,159
18493,COMPTE RENDU D'HISTOPATHOLOGIE\nPatient : Marg...,34,2 1935 05 53360 913 32,huggingChat/mistralai/Mixtral-8x7B-Instruct-v0.1,biopsie,159

In [26]:
CRO_1_et_2.to_csv(f'{file}/CRO_1_et_2.csv', index=False, sep=';')

In [58]:
new_diags = pd.read_csv('../data/diagnostics_v2.csv', sep=';', dtype=str)
diags_copy = pd.read_csv('../data/diagnostics copy.csv', sep=';', dtype=str)

In [59]:
diags_new_id = pd.merge(diags_copy, new_diags, on='diagnostic', how='left')
diags_new_id = diags_new_id.drop(["cancer", "id_label", "generation", 'statut'], axis=1)
diags_new_id = diags_new_id.rename(columns={'id_diag_x': 'id_diag'})
diags_new_id.head(5)

  organe              diagnostic id_diag id_diag_y
0   peau               psoriasis       0       277
1   peau      dermatite atopique       1        78
2   peau      lupus érythémateux       2       183
3   peau  dermatite herpétiforme       3        81
4   peau             lichen plan       4       392

In [86]:
diags_new_id.id_diag = diags_new_id.id_diag.astype(int)
diags_new_id.id_diag_y = diags_new_id.id_diag_y.astype(int)
CRO_3_transco = pd.merge(CRO_3, diags_new_id[['id_diag', 'id_diag_y']], on='id_diag', how='left')
CRO_3_transco.head(5)

,CRO,id_diag,id_med,nir,source,operation,id_diag_y
0,L'examen histopathologique de l'exérèse de pea...,20,72,1 1952 02 66734 047 03,chatGPT3.5,exérèse,82
1,Centre Hospitalier Universitaire\nService d'An...,60,7,1 1980 01 38964 514 29,chatGPT3.5,biopsie,361
2,Dr Thierry Foucher\nAnatomopathologiste\nLabor...,20,21,1 1974 06 39507 694 59,chatGPT3.5,biopsie,82
3,Compte rendu d'histopathologie\nNom de l'anato...,61,52,1 1980 01 38964 514 29,chatGPT3.5,colectomie,3
4,Compte rendu d'histopathologie\nPatient:\nNom:...,22,65,1 1986 08 87668 878 18,chatGPT3.5,exérèse,95

In [87]:
CRO_3_transco = CRO_3_transco.drop(['id_diag'], axis=1)
CRO_3_transco = CRO_3_transco.rename(columns={'id_diag_y': 'id_diag'})
CRO_3_transco.head(5)

,CRO,id_med,nir,source,operation,id_diag
0,L'examen histopathologique de l'exérèse de pea...,72,1 1952 02 66734 047 03,chatGPT3.5,exérèse,82
1,Centre Hospitalier Universitaire\nService d'An...,7,1 1980 01 38964 514 29,chatGPT3.5,biopsie,361
2,Dr Thierry Foucher\nAnatomopathologiste\nLabor...,21,1 1974 06 39507 694 59,chatGPT3.5,biopsie,82
3,Compte rendu d'histopathologie\nNom de l'anato...,52,1 1980 01 38964 514 29,chatGPT3.5,colectomie,3
4,Compte rendu d'histopathologie\nPatient:\nNom:...,65,1 1986 08 87668 878 18,chatGPT3.5,exérèse,95

In [89]:
CRO_1_et_2_et_3 = pd.concat([CRO_1_et_2, CRO_3_transco], ignore_index=True )
CRO_1_et_2_et_3.head(5)

,CRO,id_med,nir,source,operation,id_diag
0,Compte rendu d'histopathologie\nDr Valentine B...,79,2 2002 06 76416 623 45,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,175
1,Compte rendu d'histopathologie\nDr Adrienne Pa...,77,2 1955 06 74182 824 18,huggingChat/meta-llama/Llama-2-70b-chat-hf,biopsie,72
2,Compte rendu d'histopathologie\nDr Anouk Weiss...,70,1 1956 01 73544 037 28,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,2
3,Compte rendu d'histopathologie\nDr Michelle Va...,62,1 1973 02 20392 432 73,huggingChat/meta-llama/Llama-2-70b-chat-hf,exérèse,262
4,Compte rendu d'histopathologie\nLe présent rap...,3,2 1955 06 74182 824 18,huggingChat/meta-llama/Llama-2-70b-chat-hf,biopsie,32

In [90]:
CRO_1_et_2_et_3.to_csv(f'{file}/CRO_1_2_3.csv', index=False, sep=';')

In [94]:
diags_v3 = pd.read_csv('../data/diagnostics.csv', sep=';', dtype=str)
diags_new_id_bis = pd.merge(diags_v3, new_diags, on='diagnostic', how='left')
diags_new_id_bis = diags_new_id_bis.drop(["cancer", "generation", 'statut'], axis=1)
diags_new_id_bis = diags_new_id_bis.rename(columns={'id_diag_x': 'id_diag'})
diags_new_id_bis.head(5)

  organe          diagnostic id_diag id_diag_y
0   peau           psoriasis       1       277
1   peau      mélanome malin       2       243
2   peau             rosacée       3       290
3   peau  lupus érythémateux       4       183
4   peau         lichen plan       5       392

In [104]:
diags_new_id_bis = diags_new_id_bis[['id_diag', 'id_diag_y']]
diags_new_id_bis = diags_new_id_bis.astype(int)
CRO_4_transco = pd.merge(CRO_4, diags_new_id_bis, on='id_diag', how='left')
CRO_4_transco = CRO_4_transco.drop(['id_diag'], axis=1)
CRO_4_transco = CRO_4_transco.rename(columns={"id_diag_y": "id_diag"})
CRO_4_transco.head(5)

,CRO,id_med,nir,source,operation,id_diag
0,Résumé anatomo-pathologique\nPatient : Thomas ...,59,1 1980 08 14995 716 37,mistralai/Mistral-7B-Instruct-v0.2,biopsie,392
1,Résumé anatomopathologique\nPatient : Susan Ré...,8,2 1980 10 97375 990 10,mistralai/Mistral-7B-Instruct-v0.2,biopsie,272
2,Résumé anatomo-pathologique\nPatient : M Bertr...,4,1 1980 01 38964 514 29,mistralai/Mistral-7B-Instruct-v0.2,biopsie,2
3,Résumé anatomopathologique\nPatient : Mme Virg...,1,2 1935 08 30194 424 27,mistralai/Mistral-7B-Instruct-v0.2,biopsie,183
4,Résumé anatomopathologique\nPatient : M Benjam...,55,1 1948 12 72655 239 21,mistralai/Mistral-7B-Instruct-v0.2,biopsie,36

In [105]:
CRO_1_et_2_et_3_et_4 = pd.concat([CRO_1_et_2_et_3, CRO_4], ignore_index=True)
CRO_1_et_2_et_3_et_4.to_csv(f'{file}/CRO_1_2_3_4.csv', index=False, sep=';')

In [114]:
CRO = pd.concat([CRO_1_et_2_et_3_et_4, CRO_5], ignore_index=True)
CRO.to_csv(f'{file}/CRO.csv', index=False, sep=';')